# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
# Use node:lts-slim (Debian-based) instead of Alpine for better Chrome compatibility
FROM node:lts-slim

# Set working directory
WORKDIR /app

# Install Chromium with its dependencies
RUN apt-get update && apt-get install -y \
    chromium \
    --no-install-recommends \
    && rm -rf /var/lib/apt/lists/*

# Copy package files and install dependencies
# Use PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=true to avoid downloading Chromium again
ENV PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=true
COPY package.json package-lock.json ./
RUN npm install

# Copy the rest of the application files
COPY . .

# Build the TypeScript code
RUN npm run build

# Command to run the MCP server
CMD [ "node", "dist/index.js" ]
